const imdb = [
    {
        title: "Втеча з Шоушенка",
        year: 1994,
        imdb: 9.3,
        rating: 8.3,
        watched: true,
    },
    {
        title: "Хрещений батько",
        year: 1972,
        imdb: 9.2,
        rating: 8,
        watched: true,
    },
    { title: "Темний лицар", year: 2008, imdb: 9.0, rating: 9.39, watched: true },
    {
        title: "Хрещений батько 2",
        year: 1974,
        imdb: 9.0,
        rating: 8.1,
        watched: true,
    },
    {
        title: "12 розгніваних чоловіків",
        year: 1957,
        imdb: 9.0,
        rating: -1, watched: false,
    },
    {
        title: "Володар перснів: Повернення короля",
        year: 2003,
        imdb: 9.0,
        rating: 0,
        watched: true,
    },
    {
        title: "Список Шиндлера",
        year: 1993,
        imdb: 9.0,
        rating: 0,
        watched: true,
    },
    {
        title: "Кримінальне чтиво",
        year: 1994,
        imdb: 8.9,
        rating: 9,
        watched: true,
    },
    {
        title: "Володар перснів: Хранителі персня",
        year: 2001,
        imdb: 8.9,
        rating: 0,
        watched: true,
    },
    {
        title: "Хороший, поганий, злий",
        year: 1966,
        imdb: 8.8,
        rating: -1, watched: false,
    },
    { title: "Форрест Ґамп", year: 1994, imdb: 8.8, rating: -1, watched: false, },
    {
        title: "Володар перснів: Дві вежі",
        year: 2002,
        imdb: 8.8,
        rating: 0,
        watched: true,
    },
    {
        title: "Бійцівський клуб",
        year: 1999,
        imdb: 8.8,
        rating: 9,
        watched: true,
    },
    { title: "Початок", year: 2010, imdb: 8.8, rating: 0, watched: true },
    {
        title: "Зоряні війни: Епізод 5 - Імперія завдає удару у відповідь",
        year: 1980,
        imdb: 8.7,
        rating: 8,
        watched: true,
    },
    { title: "Матриця", year: 1999, imdb: 8.7, rating: 8.3, watched: true },
    { title: "Славні хлопці", year: 1990, imdb: 8.7, rating: -1, watched: false, },
    {
        title: "Пролітаючи над гніздом зозулі",
        year: 1975,
        imdb: 8.7,
        rating: -1, watched: false,
    },
    { title: "Інтерстеллар", year: 2014, imdb: 8.7, rating: 0, watched: true },
    { title: "Сім", year: 1995, imdb: 8.6, rating: -1, watched: false, },
    {
        title: "Це дивовижне життя",
        year: 1946,
        imdb: 8.6,
        rating: -1, watched: false,
    },
    { title: "Мовчання ягнят", year: 1991, imdb: 8.6, rating: -1, watched: false, },
    { title: "Сім самураїв", year: 1954, imdb: 8.6, rating: -1, watched: false, },
    {
        title: "Врятувати рядового Раяна",
        year: 1998,
        imdb: 8.6,
        rating: -1, watched: false,
    },
    { title: "Місто Бога", year: 2002, imdb: 8.6, rating: -1, watched: false, },
    { title: "Зелена миля", year: 1999, imdb: 8.6, rating: -1, watched: false, },
    {
        title: "Життя прекрасне",
        year: 1997,
        imdb: 8.6,
        rating: -1, watched: false,
    },
    {
        title: "Термінатор 2: Судний день",
        year: 1991,
        imdb: 8.6,
        rating: 0,
        watched: true,
    },
    {
        title: "Зоряні війни: Епізод 4 - Нова надія",
        year: 1977,
        imdb: 8.6,
        rating: 8,
        watched: true,
    },
    {
        title: "Назад у майбутнє",
        year: 1985,
        imdb: 8.5,
        rating: 0,
        watched: true,
    },
    {
        title: "Віднесені привидами",
        year: 2001,
        imdb: 8.6,
        rating: -1, watched: false,
    },
    { title: "Піаніст", year: 2002, imdb: 8.5, rating: -1, watched: false, },
    { title: "Гладіатор", year: 2000, imdb: 8.5, rating: -1, watched: false, },
    { title: "Паразити", year: 2019, imdb: 8.5, rating: 8.6, watched: true },
    { title: "Психо", year: 1960, imdb: 8.5, rating: -1, watched: false, },
    { title: "Король лев", year: 1994, imdb: 8.5, rating: 0, watched: true },
    {
        title: "Могила світлячків",
        year: 1988,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "Відступники", year: 2006, imdb: 8.5, rating: 9, watched: true },
    { title: "Одержимість", year: 2014, imdb: 8.5, rating: -1, watched: false, },
    { title: "Харакірі", year: 1962, imdb: 8.6, rating: -1, watched: false, },
    {
        title: "Американська історія Ікс",
        year: 1998,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "Престиж", year: 2006, imdb: 8.5, rating: 8, watched: true },
    { title: "Леон", year: 1994, imdb: 8.5, rating: 8, watched: true },
    {
        title: "Людина-павук: Крізь Всесвіт",
        year: 2023,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "Касабланка", year: 1942, imdb: 8.5, rating: -1, watched: false, },
    {
        title: "Звичайні підозрювані",
        year: 1995,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "1+1", year: 2011, imdb: 8.5, rating: -1, watched: false, },
    {
        title: "Новий кінотеатр «Парадізо»",
        year: 1988,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "Нові часи", year: 1936, imdb: 8.5, rating: -1, watched: false, },
    { title: "Чужий", year: 1979, imdb: 8.5, rating: 7.9, watched: true },
    { title: "Вікно у двір", year: 1954, imdb: 8.5, rating: -1, watched: false, },
    {
        title: "Одного разу на Дикому Заході",
        year: 1968,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "Джанго вільний", year: 2012, imdb: 8.5, rating: -1, watched: false, },
    {
        title: "Вогні великого міста",
        year: 1931,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    {
        title: "Апокаліпсис наших днів",
        year: 1979,
        imdb: 8.4,
        rating: -1, watched: false,
    },
    {
        title: "Дюна: Частина друга",
        year: 2024,
        imdb: 8.5,
        rating: 8.98,
        watched: true,
    },
    { title: "Мементо", year: 2000, imdb: 8.4, rating: -1, watched: false, },
    { title: "ВОЛЛ-І", year: 2008, imdb: 8.4, rating: 0, watched: true },
    {
        title: "Індіана Джонс: У пошуках втраченого ковчега",
        year: 1981,
        imdb: 8.4,
        rating: -1, watched: false,
    },
    { title: "Життя інших", year: 2006, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Месники: Війна нескінченності",
        year: 2018,
        imdb: 8.4,
        rating: 0,
        watched: true,
    },
    { title: "Бульвар Сансет", year: 1950, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Людина-павук: Навколо всесвіту",
        year: 2018,
        imdb: 8.4,
        rating: -1, watched: false,
    },
    { title: "Шляхи слави", year: 1957, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Свідок обвинувачення",
        year: 1957,
        imdb: 8.4,
        rating: -1, watched: false,
    },
    { title: "Сяйво", year: 1980, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Великий диктатор",
        year: 1940,
        imdb: 8.4,
        rating: -1, watched: false,
    },
    {
        title: "Дванадцята невдача",
        year: 2023,
        imdb: 8.8,
        rating: -1, watched: false,
    },
    { title: "Чужі", year: 1986, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Безславні виродки",
        year: 2009,
        imdb: 8.4,
        rating: 0,
        watched: true,
    },
    {
        title: "Темний лицар повертається",
        year: 2012,
        imdb: 8.4,
        rating: 9.7,
        watched: true,
    },
    { title: "Коко", year: 2017, imdb: 8.4, rating: -1, watched: false, },
    { title: "Амадей", year: 1984, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Історія іграшок",
        year: 1995,
        imdb: 8.3,
        rating: 0,
        watched: true,
    },
    {
        title: "Hababam Sinifi: Sinifta Kaldi",
        year: 1975,
        imdb: 8.8,
        rating: -1, watched: false,
    },
    {
        title: "Месники: Завершення",
        year: 2019,
        imdb: 8.4,
        rating: 0,
        watched: true,
    },
    {
        title: "Розумник Вілл Хантінг",
        year: 1997,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Олдбой", year: 2003, imdb: 8.3, rating: 6.7, watched: false },
    {
        title: "Доктор Стрейнджлав, або Як я перестав хвилюватись і полюбив бомбу",
        year: 1964,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "Краса по-американськи",
        year: 1999,
        imdb: 8.3,
        rating: 8,
        watched: true,
    },
    {
        title: "Підводний човен",
        year: 1981,
        imdb: 8.4,
        rating: -1, watched: false,
    },
    { title: "Хоробре серце", year: 1995, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Принцеса Мононоке",
        year: 1997,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Твоє ім'я", year: 2016, imdb: 8.4, rating: -1, watched: false, },
    { title: "Рай і пекло", year: 1963, imdb: 8.4, rating: -1, watched: false, },
    { title: "Три ідіоти", year: 2009, imdb: 8.4, rating: -1, watched: false, },
    { title: "Джокер", year: 2019, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Якось в Америці",
        year: 1984,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Капернаум", year: 2018, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Співаючи під дощем",
        year: 1952,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Іди і дивись", year: 1985, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Реквієм за мрією",
        year: 2000,
        imdb: 8.3,
        rating: 8.89,
        watched: true,
    },
    {
        title: "Історія іграшок 3",
        year: 2010,
        imdb: 8.3,
        rating: 0,
        watched: true,
    },
    {
        title: "Зоряні війни: Епізод 6 - Повернення Джедая",
        year: 1983,
        imdb: 8.3,
        rating: 7.9,
        watched: true,
    },
    { title: "Полювання", year: 2012, imdb: 8.3, rating: -1, watched: false, },
    { title: "Жити", year: 1952, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Вічне сяйво чистого розуму",
        year: 2004,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "2001: Космічна Одіссея",
        year: 1968,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Скажені пси", year: 1992, imdb: 8.3, rating: 8, watched: true },
    { title: "Квартира", year: 1960, imdb: 8.3, rating: -1, watched: false, },
    { title: "Пожежі", year: 2010, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Лоуренс Аравійський",
        year: 1962,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "Обличчя зі шрамом",
        year: 1983,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "Подвійна страховка",
        year: 1944,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "На північ через північний захід",
        year: 1959,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Сутичка", year: 1995, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Громадянин Кейн",
        year: 1941,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Вперед і вгору", year: 2009, imdb: 8.3, rating: 0, watched: true },
    {
        title: "М: Місто шукає вбивцю",
        year: 1931,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "Цілісно-металева оболонка",
        year: 1987,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Запаморочення", year: 1958, imdb: 8.3, rating: -1, watched: false, },
    { title: "Амелі", year: 2001, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Розлучення Надера і Сімін",
        year: 2011,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "Вбити пересмішника",
        year: 1962,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    {
        title: "Механічний апельсин",
        year: 1971,
        imdb: 8.2,
        rating: 7,
        watched: true,
    },
    { title: "Міцний горішок", year: 1988, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Зіроньки на Землі",
        year: 2007,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Афера", year: 1973, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Індіана Джонс і останній хрестовий похід",
        year: 1989,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Оппенгеймер", year: 2023, imdb: 8.3, rating: 7.4, watched: true },
    { title: "Метрополіс", year: 1927, imdb: 8.3, rating: -1, watched: false, },
    { title: "Великий куш", year: 2000, imdb: 8.2, rating: -1, watched: false, },
    { title: "1917", year: 2019, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Секрети Лос-Анджелеса",
        year: 1997,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    {
        title: "Викрадачі велосипедів",
        year: 1948,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Бункер", year: 2004, imdb: 8.2, rating: -1, watched: false, },
    { title: "Дангал", year: 2016, imdb: 8.3, rating: -1, watched: false, },
    { title: "Таксист", year: 1976, imdb: 8.2, rating: -1, watched: false, },
    { title: "Гамільтон", year: 2020, imdb: 8.3, rating: -1, watched: false, },
    {
        title: "Вовк з Волл-стріт",
        year: 2013,
        imdb: 8.2,
        rating: 8.5,
        watched: true,
    },
    {
        title: "Бетмен: Початок",
        year: 2005,
        imdb: 8.2,
        rating: 9.5,
        watched: true,
    },
    { title: "Зелена книга", year: 2018, imdb: 8.2, rating: 0, watched: true },
    {
        title: "На декілька доларів більше",
        year: 1965,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    {
        title: "Нюрнберзький процес",
        year: 1961,
        imdb: 8.3,
        rating: -1, watched: false,
    },
    { title: "Шоу Трумена", year: 1998, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "У джазі тільки дівчата",
        year: 1959,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    {
        title: "Острів проклятих",
        year: 2010,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Малюк", year: 1921, imdb: 8.2, rating: -1, watched: false, },
    { title: "Батько", year: 2020, imdb: 8.2, rating: -1, watched: false, },
    { title: "Усе про Єву", year: 1950, imdb: 8.2, rating: -1, watched: false, },
    { title: "Нафта", year: 2007, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Парк Юрського періоду",
        year: 1993,
        imdb: 8.2,
        rating: 0,
        watched: true,
    },
    { title: "Казино", year: 1995, imdb: 8.2, rating: -1, watched: false, },
    { title: "Шосте чуття", year: 1999, imdb: 8.2, rating: -1, watched: false, },
    { title: "Ран", year: 1985, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Найкращий стрілець: Маверік",
        year: 2022,
        imdb: 8.2,
        rating: 0,
        watched: true,
    },
    {
        title: "Старим тут не місце",
        year: 2007,
        imdb: 8.2,
        rating: 7.4,
        watched: true,
    },
    { title: "Щось", year: 1982, imdb: 8.2, rating: 7.3, watched: true },
    { title: "Лабіринт Фавна", year: 2006, imdb: 8.2, rating: -1, watched: false, },
    { title: "Непрощенний", year: 1992, imdb: 8.2, rating: -1, watched: false, },
    { title: "Ігри розуму", year: 2001, imdb: 8.2, rating: 0, watched: true },
    { title: "Убити Білла", year: 2003, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Скарби Сьєрра-Мадре",
        year: 1948,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Полонянки", year: 2013, imdb: 8.2, rating: -1, watched: false, },
    { title: "Охоронець", year: 1961, imdb: 8.2, rating: -1, watched: false, },
    { title: "У пошуках Немо", year: 2003, imdb: 8.2, rating: 0, watched: true },
    { title: "Велика втеча", year: 1963, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Мандрівний замок",
        year: 2004,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    {
        title: "Монті Пайтон і Священний Грааль",
        year: 1975,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Людина-слон", year: 1980, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "У випадку вбивства телефонуйте «М»",
        year: 1954,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    {
        title: "Віднесені вітром",
        year: 1939,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Рашьомон", year: 1950, imdb: 8.2, rating: -1, watched: false, },
    { title: "Клаус", year: 2019, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Китайський квартал",
        year: 1974,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Секрет у його очах",
        year: 2009,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    {
        title: "Карти, гроші, два стволи",
        year: 1998,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    {
        title: "«V» означає Вендетта",
        year: 2005,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    {
        title: "Думками навиворіт",
        year: 2015,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    {
        title: "Три білборди під Еббінґом, Міссурі",
        year: 2017,
        imdb: 8.1,
        rating: 8.8,
        watched: true,
    },
    {
        title: "Міст через річку Квай",
        year: 1957,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Дикий робот", year: 2024, imdb: 8.2, rating: -1, watched: false, },
    { title: "На голці", year: 1996, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Впіймай мене, якщо зможеш",
        year: 2002,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Скажений бик", year: 1980, imdb: 8.1, rating: -1, watched: false, },
    { title: "Фарґо", year: 1996, imdb: 8.1, rating: -1, watched: false, },
    { title: "Воїн", year: 2011, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Гаррі Поттер і смертельні реліквії: Частина 2",
        year: 2011,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    { title: "Гран Торіно", year: 2008, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Крихітка на мільйон доларів",
        year: 2004,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Мій сусід Тоторо",
        year: 1988,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Шалений Макс: Дорога гніву",
        year: 2015,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Людина-павук: Додому шляху нема",
        year: 2021,
        imdb: 8.2,
        rating: 7.99,
        watched: true,
    },
    { title: "Бен-Гур", year: 1959, imdb: 8.1, rating: 0, watched: true },
    { title: "Баррі Ліндон", year: 1975, imdb: 8.1, rating: -1, watched: false, },
    { title: "Діти небес", year: 1997, imdb: 8.2, rating: -1, watched: false, },
    {
        title: "Товариство мертвих поетів",
        year: 1989,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "12 років рабства",
        year: 2013,
        imdb: 8.1,
        rating: 8.1,
        watched: true,
    },
    { title: "До сходу сонця", year: 1995, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Готель «Ґранд Будапешт»",
        year: 2014,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Той, хто біжить по лезу",
        year: 1982,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "З міркувань совісті",
        year: 2016,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Загублена", year: 2014, imdb: 8.1, rating: 9.1, watched: true },
    {
        title: "Спогади про вбивство",
        year: 2003,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Я досі тут", year: 2024, imdb: 8.3, rating: -1, watched: false, },
    { title: "Рататуй", year: 2007, imdb: 8.1, rating: 0, watched: true },
    {
        title: "Корпорація монстрів",
        year: 2001,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    { title: "В ім'я батька", year: 1993, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Золота лихоманка",
        year: 1925,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Дикі історії", year: 2014, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Як приборкати дракона",
        year: 2010,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    {
        title: "Шерлок молодший",
        year: 1924,
        imdb: 8.2,
        rating: -1, watched: false,
    },
    { title: "Щелепи", year: 1975, imdb: 8.1, rating: -1, watched: false, },
    { title: "Мері та Макс", year: 2009, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Мисливець на оленів",
        year: 1978,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Генерал", year: 1926, imdb: 8.1, rating: -1, watched: false, },
    { title: "Аутсайдери", year: 2019, imdb: 8.1, rating: -1, watched: false, },
    { title: "Плата за страх", year: 1953, imdb: 8.1, rating: -1, watched: false, },
    { title: "У порту", year: 1954, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Містер Сміт їде до Вашингтона",
        year: 1939,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Сунична галявина",
        year: 1957,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Логан: Росомаха",
        year: 2017,
        imdb: 8.1,
        rating: 8,
        watched: true,
    },
    { title: "Роккі", year: 1976, imdb: 8.1, rating: -1, watched: false, },
    { title: "Третя людина", year: 1949, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Токійська історія",
        year: 1953,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Махараджа", year: 2024, imdb: 8.4, rating: -1, watched: false, },
    {
        title: "Великий Лебовські",
        year: 1998,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "У центрі уваги", year: 2015, imdb: 8.1, rating: -1, watched: false, },
    { title: "Термінатор", year: 1984, imdb: 8.1, rating: 0, watched: true },
    { title: "Сьома печатка", year: 1957, imdb: 8.1, rating: -1, watched: false, },
    { title: "Кімната", year: 2015, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Пірати Карибського моря: Прокляття Чорної перлини",
        year: 2003,
        imdb: 8.1,
        rating: 0,
        watched: true,
    },
    { title: "Ненависть", year: 1995, imdb: 8.1, rating: -1, watched: false, },
    { title: "Jai Bhim", year: 2021, imdb: 8.7, rating: -1, watched: false, },
    { title: "Готель Руанда", year: 2004, imdb: 8.1, rating: -1, watched: false, },
    { title: "Взвод", year: 1986, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Найкращі роки нашого життя",
        year: 1946,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Перед заходом сонця",
        year: 2004,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Той, що виганяє диявола",
        year: 1973,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Страсті Жанни Д'Арк",
        year: 1928,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Чарівник країни Оз",
        year: 1939,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Звуки музики", year: 1965, imdb: 8.1, rating: -1, watched: false, },
    { title: "Суперсімейка", year: 2004, imdb: 8.0, rating: 0, watched: true },
    { title: "Гонка", year: 2013, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Хатіко: Вірний друг",
        year: 2009,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Залишся зі мною",
        year: 1986,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Телемережа", year: 1976, imdb: 8.1, rating: -1, watched: false, },
    { title: "Батько та Син", year: 2005, imdb: 8.2, rating: -1, watched: false, },
    { title: "Служниця", year: 2016, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Залізний велетень",
        year: 1999,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    {
        title: "Бути чи не бути",
        year: 1942,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Битва за Алжир", year: 1966, imdb: 8.1, rating: -1, watched: false, },
    { title: "Грона гніву", year: 1940, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Тепер я йду у дику далечінь",
        year: 2007,
        imdb: 8.1,
        rating: -1, watched: false,
    },
    { title: "Форма голосу", year: 2016, imdb: 8.1, rating: -1, watched: false, },
    {
        title: "Kimetsu no Yaiba: Tsuzumi Yashiki-hen",
        year: 2021,
        imdb: 8.5,
        rating: -1, watched: false,
    },
    { title: "День бабака", year: 1993, imdb: 8.0, rating: -1, watched: false, },
    { title: "Прислуга", year: 2011, imdb: 8.1, rating: -1, watched: false, },
    { title: "Сука любов", year: 2000, imdb: 8.0, rating: -1, watched: false, },
    { title: "Ребекка", year: 1940, imdb: 8.1, rating: -1, watched: false, },
];

export default imdb;
